FROM nvcr.io/nvidia/pytorch:25.08-py3

# Set noninteractive mode
ENV DEBIAN_FRONTEND=noninteractive

# Install system packages
RUN apt-get update && apt-get install -y \
    git wget sudo nano curl unzip build-essential cmake ninja-build \
    python3 python3-pip python3-dev python-is-python3 python3-tk\
    libglib2.0-0 libsm6 libxext6 libxrender-dev \
    # libgl1-mesa-glx libgl1-mesa-dri ffmpeg \ 
    && rm -rf /var/lib/apt/lists/*

# Upgrade pip
RUN python -m pip install --upgrade pip

# Install PyTorch 2.0.1 (CUDA 11.8)
# RUN pip install torch==2.0.1+cu118 torchvision==0.15.2+cu118 torchaudio==2.0.2+cu118 --extra-index-url https://download.pytorch.org/whl/cu118

RUN pip install -U tqdm matplotlib

# Install transformers from Hugging Face
RUN pip install transformers tiktoken timm wandb

# Add user ubuntu and set permissions
# RUN useradd -m -s /bin/bash ubuntu && \
#     echo "ubuntu ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers && \
#     chown -R ubuntu: /home/ubuntu

# Add bashrc
COPY ./.devcontainer/.bashrc /home/ubuntu/.bashrc
RUN chown ubuntu: /home/ubuntu/.bashrc

# Switch to user ubuntu
USER ubuntu

# Set working directory
WORKDIR /home/ubuntu

CMD ["/bin/bash"]
